// <auto-generated />
using System;
using FridgeManager.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FridgeManager.Domain.Migrations
{
    [DbContext(typeof(FridgeManagerDbContext))]
    [Migration("20220531173534_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FridgeManager.Domain.Models.Authorization.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "670bfcb7-eea4-4e8d-aa67-aaf92aa52843",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1603965f-bbec-4643-8556-6037ba20e857",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Login = "admin",
                            Password = "1111",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fbbf0e9c-4dd4-4282-8741-83babc102f98",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("FridgeManager.Domain.Models.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Fridges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ae570a2-589e-4ff9-9832-fea046205188"),
                            ModelId = new Guid("dd50828f-2c44-4f1c-a8ec-904eca7807fc"),
                            Name = "Vestfrost",
                            OwnerName = "Polina"
                        },
                        new
                        {
                            Id = new Guid("769382a4-fa6c-4164-8f31-e888f4462e7a"),
                            ModelId = new Guid("bd03b24d-21a1-4a29-8143-1bbf2fb7c420"),
                            Name = "Vestfrost",
                            OwnerName = "Anna"
                        },
                        new
                        {
                            Id = new Guid("78a99e33-44be-495b-b467-b18f17b96a14"),
                            ModelId = new Guid("2fe3f442-f3ed-43f1-bb53-83dda806b73e"),
                            Name = "Philyps",
                            OwnerName = "Andrew"
                        },
                        new
                        {
                            Id = new Guid("5ced85cc-91e1-4dfb-adb9-7b9ac3281aa0"),
                            ModelId = new Guid("620217d9-13d6-464a-825e-b2f76f0bd1b8"),
                            Name = "Atlant",
                            OwnerName = "Mariya"
                        },
                        new
                        {
                            Id = new Guid("212c1e35-032e-4148-b6f1-1b75c50fabf5"),
                            ModelId = new Guid("2fe3f442-f3ed-43f1-bb53-83dda806b73e"),
                            Name = "Philyps",
                            OwnerName = "Kirill"
                        },
                        new
                        {
                            Id = new Guid("ed0b7205-305f-4a33-af0a-e1d13d03f2db"),
                            ModelId = new Guid("33913e15-8500-4aaa-9276-f780baca2d25"),
                            Name = "Indesit",
                            OwnerName = "Dima"
                        },
                        new
                        {
                            Id = new Guid("cfacab37-e467-43d4-847a-324c0a4187d0"),
                            ModelId = new Guid("880a72b6-a965-4fcb-a57c-8abe0b5de2eb"),
                            Name = "Stinol",
                            OwnerName = "Julia"
                        },
                        new
                        {
                            Id = new Guid("767da512-da4c-4493-88a6-69fcdb7119a3"),
                            ModelId = new Guid("7c989aea-8af6-47f0-aa37-5e72ee135e48"),
                            Name = "Indesit",
                            OwnerName = "Nastya"
                        },
                        new
                        {
                            Id = new Guid("8402b2de-ddc9-4f21-afbb-416b6c1a52ff"),
                            ModelId = new Guid("33913e15-8500-4aaa-9276-f780baca2d25"),
                            Name = "Philyps",
                            OwnerName = "Kirill"
                        },
                        new
                        {
                            Id = new Guid("7a18ffa0-4981-4f4e-8798-29117fcda03e"),
                            ModelId = new Guid("57304f9e-686c-49b6-bf29-14662df14799"),
                            Name = "Atlant",
                            OwnerName = "Dima"
                        },
                        new
                        {
                            Id = new Guid("141ca1e9-ff46-45e3-a98f-88bae9e44d7a"),
                            ModelId = new Guid("97751dcf-f688-49e2-8942-d0c310507ed5"),
                            Name = "Liebherr",
                            OwnerName = "Andrew"
                        },
                        new
                        {
                            Id = new Guid("0353dcde-2cf8-489e-9196-82312867099e"),
                            ModelId = new Guid("4606b3a9-7e90-454b-99e2-6b920c54de54"),
                            Name = "Bosh",
                            OwnerName = "Mariya"
                        },
                        new
                        {
                            Id = new Guid("fc749100-f9d6-4db9-9652-421eacf3564d"),
                            ModelId = new Guid("2fe3f442-f3ed-43f1-bb53-83dda806b73e"),
                            Name = "Philyps",
                            OwnerName = "Anna"
                        },
                        new
                        {
                            Id = new Guid("97aa80bd-112f-4d67-8527-81e9561083b0"),
                            ModelId = new Guid("97751dcf-f688-49e2-8942-d0c310507ed5"),
                            Name = "Liebherr",
                            OwnerName = "Polina"
                        },
                        new
                        {
                            Id = new Guid("70a4261b-bb48-438e-afd4-3b77bbf681fa"),
                            ModelId = new Guid("880a72b6-a965-4fcb-a57c-8abe0b5de2eb"),
                            Name = "Bosh",
                            OwnerName = "Vlada"
                        },
                        new
                        {
                            Id = new Guid("4cd75302-46b3-4a73-84d3-f8d777e70d6c"),
                            ModelId = new Guid("d23f1e56-af45-4577-904a-62226fe09920"),
                            Name = "Philyps",
                            OwnerName = "Polina"
                        },
                        new
                        {
                            Id = new Guid("954fe4b3-f1c7-4b70-93e2-7776ed444956"),
                            ModelId = new Guid("620217d9-13d6-464a-825e-b2f76f0bd1b8"),
                            Name = "Atlant",
                            OwnerName = "Vlada"
                        },
                        new
                        {
                            Id = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ModelId = new Guid("419f55fd-235e-4567-8e2b-8628d68c5184"),
                            Name = "Vestfrost",
                            OwnerName = "Polina"
                        },
                        new
                        {
                            Id = new Guid("8f9a4593-1bfb-4a1b-b374-279cd5eeed42"),
                            ModelId = new Guid("57304f9e-686c-49b6-bf29-14662df14799"),
                            Name = "Indesit",
                            OwnerName = "Dima"
                        },
                        new
                        {
                            Id = new Guid("a43caaad-81ae-4fa2-a26e-c4d2e39ed803"),
                            ModelId = new Guid("2fe3f442-f3ed-43f1-bb53-83dda806b73e"),
                            Name = "Beko",
                            OwnerName = "Andrew"
                        });
                });

            modelBuilder.Entity("FridgeManager.Domain.Models.FridgeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FridgeModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("620217d9-13d6-464a-825e-b2f76f0bd1b8"),
                            Name = "TH-803",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("57304f9e-686c-49b6-bf29-14662df14799"),
                            Name = "514-NWE",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("bd03b24d-21a1-4a29-8143-1bbf2fb7c420"),
                            Name = "RC-54",
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("2fe3f442-f3ed-43f1-bb53-83dda806b73e"),
                            Name = "XM 4021-000",
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("a64c6470-79b6-437f-beac-08eeb3955565"),
                            Name = "DF 5180 W",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("d23f1e56-af45-4577-904a-62226fe09920"),
                            Name = "DS 333020",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("7c989aea-8af6-47f0-aa37-5e72ee135e48"),
                            Name = "VF 466 EB",
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("4606b3a9-7e90-454b-99e2-6b920c54de54"),
                            Name = "KGN36S55",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("9f6270f6-0526-4be6-bd80-8c217c1dadd6"),
                            Name = "RB-34 K6220SS",
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("dd50828f-2c44-4f1c-a8ec-904eca7807fc"),
                            Name = "VF 910 X",
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("33913e15-8500-4aaa-9276-f780baca2d25"),
                            Name = "Electric MR-CR46G-HS-R",
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("c8de2473-ff5b-4900-8b4f-128e6d4534c6"),
                            Name = "RF-61 K90407F",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("97751dcf-f688-49e2-8942-d0c310507ed5"),
                            Name = "SBS 7212",
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("419f55fd-235e-4567-8e2b-8628d68c5184"),
                            Name = "VF 395-1 SBS",
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("880a72b6-a965-4fcb-a57c-8abe0b5de2eb"),
                            Name = "RSA1SHVB1",
                            Year = 2011
                        });
                });

            modelBuilder.Entity("FridgeManager.Domain.Models.FridgeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ProductId");

                    b.ToTable("FridgeProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28b4074d-2e61-479d-b452-eea556a5174b"),
                            FridgeId = new Guid("97aa80bd-112f-4d67-8527-81e9561083b0"),
                            ProductId = new Guid("1719d983-68fb-4ebf-9ac3-ac52dd78f052"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("5ef9816c-452c-48cc-9eaa-98f5c7b0fc1c"),
                            FridgeId = new Guid("5ced85cc-91e1-4dfb-adb9-7b9ac3281aa0"),
                            ProductId = new Guid("bdda92b3-5e80-40cd-8dcd-9b1b2e2b473b"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("27fb0f8f-18ca-4452-bb1a-22411484ffc9"),
                            FridgeId = new Guid("141ca1e9-ff46-45e3-a98f-88bae9e44d7a"),
                            ProductId = new Guid("5ca1249a-e85b-4c1f-a905-8491904144ef"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("1468f0ec-9aac-4eb2-8386-498457d56ab1"),
                            FridgeId = new Guid("954fe4b3-f1c7-4b70-93e2-7776ed444956"),
                            ProductId = new Guid("1d98c8d2-e0fb-41b5-b9d7-80191cb89e3e"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("97653727-109f-4344-8d38-cd72907af9dd"),
                            FridgeId = new Guid("78a99e33-44be-495b-b467-b18f17b96a14"),
                            ProductId = new Guid("47a3cd4c-708f-4b1d-aa2e-1e4bc2c29d55"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("84ad049b-b9b5-4766-9595-a7e395b62e0b"),
                            FridgeId = new Guid("5ced85cc-91e1-4dfb-adb9-7b9ac3281aa0"),
                            ProductId = new Guid("e8f8756a-2672-4d6d-8d8d-a58beaaa7ce2"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("de889268-f5d5-41a2-9aae-1672da22e0ae"),
                            FridgeId = new Guid("767da512-da4c-4493-88a6-69fcdb7119a3"),
                            ProductId = new Guid("23b60a97-dd73-4e06-a19e-fccb299d5fdf"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("d36497ed-428d-4652-8cde-28ef9e545d9b"),
                            FridgeId = new Guid("4cd75302-46b3-4a73-84d3-f8d777e70d6c"),
                            ProductId = new Guid("5a0c43b4-e5c9-4733-96ce-838a36869e5d"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("705add86-dbe6-4f7f-8011-1546f4bfcf3e"),
                            FridgeId = new Guid("2ae570a2-589e-4ff9-9832-fea046205188"),
                            ProductId = new Guid("b8e0f4c7-3abe-4707-994b-1aa8e959e458"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("5d23506f-bbe7-49ef-b406-5d39a3f07a78"),
                            FridgeId = new Guid("4cd75302-46b3-4a73-84d3-f8d777e70d6c"),
                            ProductId = new Guid("29cc9704-537f-4fdb-828a-d79316737017"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("e20f8605-a3e8-44f7-a908-ff377d7b7213"),
                            FridgeId = new Guid("2ae570a2-589e-4ff9-9832-fea046205188"),
                            ProductId = new Guid("67e975f4-973e-4a2a-ab4c-3b56523c99db"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("b69778a2-03b2-404b-b192-e7d668df20b5"),
                            FridgeId = new Guid("ed0b7205-305f-4a33-af0a-e1d13d03f2db"),
                            ProductId = new Guid("77fa2bef-4774-4bbe-8eb2-7cfd9c87ae9d"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("8cd3eda3-f674-45d6-9612-31b42a1f6c26"),
                            FridgeId = new Guid("a43caaad-81ae-4fa2-a26e-c4d2e39ed803"),
                            ProductId = new Guid("70cb93dd-a516-4964-9743-4c056b4ab3a8"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("b2d7d7f7-7a17-4754-a647-b09529329324"),
                            FridgeId = new Guid("8f9a4593-1bfb-4a1b-b374-279cd5eeed42"),
                            ProductId = new Guid("e65fc433-443b-4657-850b-0e51305dee31"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("78d006e7-4820-4670-9bbd-0eb110edebbf"),
                            FridgeId = new Guid("78a99e33-44be-495b-b467-b18f17b96a14"),
                            ProductId = new Guid("a1f996e4-e463-44fa-9f35-cf55aa53d8cc"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("812bb11e-c5ec-4e29-9583-8a02ef11f885"),
                            FridgeId = new Guid("8402b2de-ddc9-4f21-afbb-416b6c1a52ff"),
                            ProductId = new Guid("23b60a97-dd73-4e06-a19e-fccb299d5fdf"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("31d35600-df2f-4a4c-969a-e36528e4e7b3"),
                            FridgeId = new Guid("769382a4-fa6c-4164-8f31-e888f4462e7a"),
                            ProductId = new Guid("116741f5-917f-475b-9cb1-120d4c55caef"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("1ec26191-8a1f-4cc5-957d-1497e53a25cd"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("918368ca-4c27-4268-881f-3bed5dacd96f"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("09865aec-3de7-4ab5-b212-e812190e07fa"),
                            FridgeId = new Guid("0353dcde-2cf8-489e-9196-82312867099e"),
                            ProductId = new Guid("a1f996e4-e463-44fa-9f35-cf55aa53d8cc"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("09ac0fe0-cc72-4dbc-889b-973dec4c4427"),
                            FridgeId = new Guid("cfacab37-e467-43d4-847a-324c0a4187d0"),
                            ProductId = new Guid("a132254c-85de-4b5c-9a6e-f1c133292b5c"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("af07edf2-2c9c-4c5c-a695-01ae99cb9423"),
                            FridgeId = new Guid("7a18ffa0-4981-4f4e-8798-29117fcda03e"),
                            ProductId = new Guid("16f92d8b-d8de-409d-87a6-58743a0291c8"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("fcb5cf8a-d1ef-44b2-a8a1-0c0143ce84eb"),
                            FridgeId = new Guid("767da512-da4c-4493-88a6-69fcdb7119a3"),
                            ProductId = new Guid("c8046b78-b45e-4b92-b176-dc4b33851105"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("7cf164d0-5c1a-4c1b-9c1e-415c9aa54171"),
                            FridgeId = new Guid("769382a4-fa6c-4164-8f31-e888f4462e7a"),
                            ProductId = new Guid("5ca1249a-e85b-4c1f-a905-8491904144ef"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("16fb79ab-a0a7-41fb-99a3-fe77a6a65960"),
                            FridgeId = new Guid("954fe4b3-f1c7-4b70-93e2-7776ed444956"),
                            ProductId = new Guid("b8c66265-ae6b-40d4-a4e6-e8f0fca2820b"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("45a5c2a5-f3de-41f6-b7a0-c8b7eb6d2b51"),
                            FridgeId = new Guid("141ca1e9-ff46-45e3-a98f-88bae9e44d7a"),
                            ProductId = new Guid("8e83ae7b-760e-4e83-a5fa-862614908cca"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("a612a880-01b2-4a03-ba8b-dec81088e337"),
                            FridgeId = new Guid("4cd75302-46b3-4a73-84d3-f8d777e70d6c"),
                            ProductId = new Guid("375601c3-051a-4d8c-8c56-f6515d481d82"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("11185b85-23b3-4780-884c-ed80a33bd4e5"),
                            FridgeId = new Guid("7a18ffa0-4981-4f4e-8798-29117fcda03e"),
                            ProductId = new Guid("09bcc40f-4987-4a41-aa4c-b181404984a4"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("b255aee6-8e12-422e-9022-cd0bd68b08bb"),
                            FridgeId = new Guid("70a4261b-bb48-438e-afd4-3b77bbf681fa"),
                            ProductId = new Guid("26551416-60d1-479b-8254-296b43b00f93"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("3e6a5590-6fa7-40b5-b0ce-0f5a25593790"),
                            FridgeId = new Guid("8f9a4593-1bfb-4a1b-b374-279cd5eeed42"),
                            ProductId = new Guid("09bcc40f-4987-4a41-aa4c-b181404984a4"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("b2791415-c97d-4b26-8d0b-eabe66565054"),
                            FridgeId = new Guid("2ae570a2-589e-4ff9-9832-fea046205188"),
                            ProductId = new Guid("1719d983-68fb-4ebf-9ac3-ac52dd78f052"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("f5997b2c-6f5a-46a6-98da-42436d36c49f"),
                            FridgeId = new Guid("7a18ffa0-4981-4f4e-8798-29117fcda03e"),
                            ProductId = new Guid("b8e0f4c7-3abe-4707-994b-1aa8e959e458"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("bf216db2-fe97-4f71-b04d-c088de245898"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("23b60a97-dd73-4e06-a19e-fccb299d5fdf"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("e0aa7433-4964-42cd-8909-0ac35be32608"),
                            FridgeId = new Guid("769382a4-fa6c-4164-8f31-e888f4462e7a"),
                            ProductId = new Guid("5ca1249a-e85b-4c1f-a905-8491904144ef"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("f065bfa8-f2c1-4d16-ad4e-ba7db196b84f"),
                            FridgeId = new Guid("954fe4b3-f1c7-4b70-93e2-7776ed444956"),
                            ProductId = new Guid("918368ca-4c27-4268-881f-3bed5dacd96f"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("500a20b5-a377-4ddb-ac24-d1b88eaeff95"),
                            FridgeId = new Guid("141ca1e9-ff46-45e3-a98f-88bae9e44d7a"),
                            ProductId = new Guid("8e83ae7b-760e-4e83-a5fa-862614908cca"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("ff75553b-5ec7-4ddd-9c5e-9d9a7d0aaa7e"),
                            FridgeId = new Guid("212c1e35-032e-4148-b6f1-1b75c50fabf5"),
                            ProductId = new Guid("66e6180f-6800-4529-be7e-fe94cf1a54ca"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("35220630-e418-49cc-9866-2ce53135d129"),
                            FridgeId = new Guid("a43caaad-81ae-4fa2-a26e-c4d2e39ed803"),
                            ProductId = new Guid("16f92d8b-d8de-409d-87a6-58743a0291c8"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("6e427c52-936c-41a2-a7d7-f0301195fe7d"),
                            FridgeId = new Guid("767da512-da4c-4493-88a6-69fcdb7119a3"),
                            ProductId = new Guid("430a93be-3ce6-45f6-8247-658d44f1f490"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("6d965cfd-ae92-4b3c-935c-e5aaba89e8dc"),
                            FridgeId = new Guid("769382a4-fa6c-4164-8f31-e888f4462e7a"),
                            ProductId = new Guid("63cf83af-dad8-4194-88e9-39be803f7678"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("2855ae15-c661-458f-b5a1-902aa52a168e"),
                            FridgeId = new Guid("8402b2de-ddc9-4f21-afbb-416b6c1a52ff"),
                            ProductId = new Guid("e65fc433-443b-4657-850b-0e51305dee31"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("f9607951-f8b8-4ab5-8829-e1eef564f206"),
                            FridgeId = new Guid("fc749100-f9d6-4db9-9652-421eacf3564d"),
                            ProductId = new Guid("e8f8756a-2672-4d6d-8d8d-a58beaaa7ce2"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("6f464f52-14da-4100-a37b-dbc2bf7a1a4d"),
                            FridgeId = new Guid("767da512-da4c-4493-88a6-69fcdb7119a3"),
                            ProductId = new Guid("430a93be-3ce6-45f6-8247-658d44f1f490"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("a018f5a6-bb93-4bba-ba7c-d0d55ea49d3d"),
                            FridgeId = new Guid("769382a4-fa6c-4164-8f31-e888f4462e7a"),
                            ProductId = new Guid("8e83ae7b-760e-4e83-a5fa-862614908cca"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("40d2a02b-7806-4863-afea-0a3e3ac9061a"),
                            FridgeId = new Guid("212c1e35-032e-4148-b6f1-1b75c50fabf5"),
                            ProductId = new Guid("29cc9704-537f-4fdb-828a-d79316737017"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("cd05e672-65be-4203-a8ca-4caf5a981ecc"),
                            FridgeId = new Guid("7a18ffa0-4981-4f4e-8798-29117fcda03e"),
                            ProductId = new Guid("16f92d8b-d8de-409d-87a6-58743a0291c8"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("38b1bee2-140a-42d0-9b9d-d8ffb2059ecf"),
                            FridgeId = new Guid("cfacab37-e467-43d4-847a-324c0a4187d0"),
                            ProductId = new Guid("1d98c8d2-e0fb-41b5-b9d7-80191cb89e3e"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("def8355c-c3d3-428d-a563-433bff596d98"),
                            FridgeId = new Guid("141ca1e9-ff46-45e3-a98f-88bae9e44d7a"),
                            ProductId = new Guid("8e83ae7b-760e-4e83-a5fa-862614908cca"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("00cd8d81-0508-426b-86c4-872713718786"),
                            FridgeId = new Guid("954fe4b3-f1c7-4b70-93e2-7776ed444956"),
                            ProductId = new Guid("b8c66265-ae6b-40d4-a4e6-e8f0fca2820b"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("0adccc17-e9a3-49c6-9d99-7a29cfa3d7a3"),
                            FridgeId = new Guid("141ca1e9-ff46-45e3-a98f-88bae9e44d7a"),
                            ProductId = new Guid("bdda92b3-5e80-40cd-8dcd-9b1b2e2b473b"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("a9c6a4d4-9b80-461d-beba-22735111c2c2"),
                            FridgeId = new Guid("ed0b7205-305f-4a33-af0a-e1d13d03f2db"),
                            ProductId = new Guid("66e6180f-6800-4529-be7e-fe94cf1a54ca"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("485db49d-ad36-48b0-b296-de47706ef8fc"),
                            FridgeId = new Guid("2ae570a2-589e-4ff9-9832-fea046205188"),
                            ProductId = new Guid("8e83ae7b-760e-4e83-a5fa-862614908cca"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("3d32cd6e-a20c-4ccc-9aa2-7f285102a6d8"),
                            FridgeId = new Guid("4cd75302-46b3-4a73-84d3-f8d777e70d6c"),
                            ProductId = new Guid("a132254c-85de-4b5c-9a6e-f1c133292b5c"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("75ed3a5f-3b11-48bd-98c4-055c831231c5"),
                            FridgeId = new Guid("a43caaad-81ae-4fa2-a26e-c4d2e39ed803"),
                            ProductId = new Guid("bdda92b3-5e80-40cd-8dcd-9b1b2e2b473b"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("f617e840-e570-404e-b5f8-4edd50a78acc"),
                            FridgeId = new Guid("212c1e35-032e-4148-b6f1-1b75c50fabf5"),
                            ProductId = new Guid("23b60a97-dd73-4e06-a19e-fccb299d5fdf"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("71517df5-c8e9-438b-901f-22ee1b42790e"),
                            FridgeId = new Guid("fc749100-f9d6-4db9-9652-421eacf3564d"),
                            ProductId = new Guid("a1f996e4-e463-44fa-9f35-cf55aa53d8cc"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("4a82968e-0c79-4c69-98ec-bca9b16d1f1c"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("e65fc433-443b-4657-850b-0e51305dee31"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("f2556f63-8cdc-4865-a05a-f30c4958b225"),
                            FridgeId = new Guid("78a99e33-44be-495b-b467-b18f17b96a14"),
                            ProductId = new Guid("63cf83af-dad8-4194-88e9-39be803f7678"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("f474dae7-49e5-4b14-9a51-0c8c47b00bf3"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("13a10290-240e-4bae-bc72-129275177cf2"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("66074371-ab7e-49e8-aa20-b2eece09c59d"),
                            FridgeId = new Guid("0353dcde-2cf8-489e-9196-82312867099e"),
                            ProductId = new Guid("8e83ae7b-760e-4e83-a5fa-862614908cca"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("5e8eb2cd-981b-43ed-91ba-c986b51afe37"),
                            FridgeId = new Guid("4cd75302-46b3-4a73-84d3-f8d777e70d6c"),
                            ProductId = new Guid("77fa2bef-4774-4bbe-8eb2-7cfd9c87ae9d"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("d6102e1f-6e20-43d6-a169-4383a9c5e6f7"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("430a93be-3ce6-45f6-8247-658d44f1f490"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("0ed5e7b8-ca82-41b9-93ad-508e1c4dc417"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("bdda92b3-5e80-40cd-8dcd-9b1b2e2b473b"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("da0debae-a9aa-45a5-adea-9af1dac961ba"),
                            FridgeId = new Guid("141ca1e9-ff46-45e3-a98f-88bae9e44d7a"),
                            ProductId = new Guid("e65fc433-443b-4657-850b-0e51305dee31"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("44a73290-7af9-4907-bde9-947e2bd52070"),
                            FridgeId = new Guid("769382a4-fa6c-4164-8f31-e888f4462e7a"),
                            ProductId = new Guid("b8e0f4c7-3abe-4707-994b-1aa8e959e458"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("186e08b4-6ae7-4aec-98e2-66eb94d90b36"),
                            FridgeId = new Guid("78a99e33-44be-495b-b467-b18f17b96a14"),
                            ProductId = new Guid("67e975f4-973e-4a2a-ab4c-3b56523c99db"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("b0ba0aba-5924-42a5-a30d-6f3e5b8e1b29"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("1d98c8d2-e0fb-41b5-b9d7-80191cb89e3e"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("7c640f6f-7fea-44f0-bd72-de9f6085787f"),
                            FridgeId = new Guid("8402b2de-ddc9-4f21-afbb-416b6c1a52ff"),
                            ProductId = new Guid("23b60a97-dd73-4e06-a19e-fccb299d5fdf"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("32326368-8c25-446c-86c4-5f86a983d3a6"),
                            FridgeId = new Guid("a43caaad-81ae-4fa2-a26e-c4d2e39ed803"),
                            ProductId = new Guid("13a10290-240e-4bae-bc72-129275177cf2"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("6d13a135-c3fd-46c2-b71f-d3a9149ec22d"),
                            FridgeId = new Guid("767da512-da4c-4493-88a6-69fcdb7119a3"),
                            ProductId = new Guid("1013bc0a-821b-4880-a911-cca740cd8616"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("97fa80db-2e24-45a6-9fa6-14b41e4b8e5e"),
                            FridgeId = new Guid("0353dcde-2cf8-489e-9196-82312867099e"),
                            ProductId = new Guid("bdda92b3-5e80-40cd-8dcd-9b1b2e2b473b"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("3b3d8205-9a31-4327-8068-0802c009280f"),
                            FridgeId = new Guid("2ae570a2-589e-4ff9-9832-fea046205188"),
                            ProductId = new Guid("09bcc40f-4987-4a41-aa4c-b181404984a4"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("ed1919d7-76e9-481b-8cb7-8a83aab35f29"),
                            FridgeId = new Guid("78a99e33-44be-495b-b467-b18f17b96a14"),
                            ProductId = new Guid("8e83ae7b-760e-4e83-a5fa-862614908cca"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("2c87fe91-8b14-45f7-b789-207e3527f869"),
                            FridgeId = new Guid("0353dcde-2cf8-489e-9196-82312867099e"),
                            ProductId = new Guid("bdda92b3-5e80-40cd-8dcd-9b1b2e2b473b"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("372022ac-a6e3-43ba-b30d-d90376bcabaa"),
                            FridgeId = new Guid("2ae570a2-589e-4ff9-9832-fea046205188"),
                            ProductId = new Guid("09bcc40f-4987-4a41-aa4c-b181404984a4"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("48ed8739-11db-421e-99ce-37513b2fc788"),
                            FridgeId = new Guid("78a99e33-44be-495b-b467-b18f17b96a14"),
                            ProductId = new Guid("a1f996e4-e463-44fa-9f35-cf55aa53d8cc"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("4e732040-9f80-41f1-b0aa-0f608bf1eb91"),
                            FridgeId = new Guid("212c1e35-032e-4148-b6f1-1b75c50fabf5"),
                            ProductId = new Guid("116741f5-917f-475b-9cb1-120d4c55caef"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("9e643773-e915-4d27-ad45-42a5d8257a09"),
                            FridgeId = new Guid("ed0b7205-305f-4a33-af0a-e1d13d03f2db"),
                            ProductId = new Guid("3ecb1585-78ca-4105-b96c-a1eb56527838"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("bf0bfc6f-ec21-4719-a081-38105aee6b2e"),
                            FridgeId = new Guid("0353dcde-2cf8-489e-9196-82312867099e"),
                            ProductId = new Guid("63cf83af-dad8-4194-88e9-39be803f7678"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("aed7e655-4020-41a6-9775-87fb03683467"),
                            FridgeId = new Guid("4cd75302-46b3-4a73-84d3-f8d777e70d6c"),
                            ProductId = new Guid("1719d983-68fb-4ebf-9ac3-ac52dd78f052"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("9d857447-971e-4190-9c3a-67bc5c93c86d"),
                            FridgeId = new Guid("8402b2de-ddc9-4f21-afbb-416b6c1a52ff"),
                            ProductId = new Guid("918368ca-4c27-4268-881f-3bed5dacd96f"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("fa01c29d-dcea-4a18-afb8-517a6c69e3e6"),
                            FridgeId = new Guid("141ca1e9-ff46-45e3-a98f-88bae9e44d7a"),
                            ProductId = new Guid("bdda92b3-5e80-40cd-8dcd-9b1b2e2b473b"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("5c30022b-58a3-47d4-853b-5bab5aead201"),
                            FridgeId = new Guid("5ced85cc-91e1-4dfb-adb9-7b9ac3281aa0"),
                            ProductId = new Guid("256e2500-3c66-47ad-a2f7-410b33552aea"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("e2051469-5212-41c2-a461-66433d345f1e"),
                            FridgeId = new Guid("954fe4b3-f1c7-4b70-93e2-7776ed444956"),
                            ProductId = new Guid("b8c66265-ae6b-40d4-a4e6-e8f0fca2820b"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("c5f3d0b6-ae7f-4fc6-9397-b11bb8a93c2e"),
                            FridgeId = new Guid("0353dcde-2cf8-489e-9196-82312867099e"),
                            ProductId = new Guid("63cf83af-dad8-4194-88e9-39be803f7678"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("7b37810e-b3c4-4b09-a8da-0d37ada984d0"),
                            FridgeId = new Guid("70a4261b-bb48-438e-afd4-3b77bbf681fa"),
                            ProductId = new Guid("166160aa-2cf5-4635-b7ee-1d43b7be2463"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("b90fd5d7-dfd1-42f4-bd46-4da23f9ac393"),
                            FridgeId = new Guid("141ca1e9-ff46-45e3-a98f-88bae9e44d7a"),
                            ProductId = new Guid("bdda92b3-5e80-40cd-8dcd-9b1b2e2b473b"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("1e8fed45-5c3e-4da3-82b6-68a3dbcba45a"),
                            FridgeId = new Guid("5ced85cc-91e1-4dfb-adb9-7b9ac3281aa0"),
                            ProductId = new Guid("116741f5-917f-475b-9cb1-120d4c55caef"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("930d49c5-00c3-4870-950b-ef8672890ab9"),
                            FridgeId = new Guid("ed0b7205-305f-4a33-af0a-e1d13d03f2db"),
                            ProductId = new Guid("26551416-60d1-479b-8254-296b43b00f93"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("8ae09e44-0c59-4a24-b4c3-385cb11cb824"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("23b60a97-dd73-4e06-a19e-fccb299d5fdf"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("e4292d18-47ce-4477-8bb7-c8cfc904bf65"),
                            FridgeId = new Guid("769382a4-fa6c-4164-8f31-e888f4462e7a"),
                            ProductId = new Guid("799f487a-df41-4bd6-86bf-5e00d7b02941"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("84c8a30c-0568-4769-9c84-fc9ae8cb9015"),
                            FridgeId = new Guid("4cd75302-46b3-4a73-84d3-f8d777e70d6c"),
                            ProductId = new Guid("375601c3-051a-4d8c-8c56-f6515d481d82"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("964fa4dc-b006-49f0-b275-c458465dd339"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("918368ca-4c27-4268-881f-3bed5dacd96f"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("2f341d89-bd00-4448-aa30-0fbd4d6bf5ec"),
                            FridgeId = new Guid("0353dcde-2cf8-489e-9196-82312867099e"),
                            ProductId = new Guid("b8e0f4c7-3abe-4707-994b-1aa8e959e458"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("4efa898a-95e1-4df6-8d00-217ce93214d6"),
                            FridgeId = new Guid("e43b547d-8e78-4853-ab2d-40a5eddbc23b"),
                            ProductId = new Guid("13a10290-240e-4bae-bc72-129275177cf2"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("82f54c11-8bb5-4117-ae64-63a648de1c8a"),
                            FridgeId = new Guid("2ae570a2-589e-4ff9-9832-fea046205188"),
                            ProductId = new Guid("16f92d8b-d8de-409d-87a6-58743a0291c8"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("5e915805-fa71-4b96-8523-ac73462fe446"),
                            FridgeId = new Guid("4cd75302-46b3-4a73-84d3-f8d777e70d6c"),
                            ProductId = new Guid("375601c3-051a-4d8c-8c56-f6515d481d82"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("9977aeb1-9b80-4c1a-b4dc-1f24b9efcd47"),
                            FridgeId = new Guid("8402b2de-ddc9-4f21-afbb-416b6c1a52ff"),
                            ProductId = new Guid("c8046b78-b45e-4b92-b176-dc4b33851105"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("8833ddbd-2a47-447e-a218-64a072917398"),
                            FridgeId = new Guid("0353dcde-2cf8-489e-9196-82312867099e"),
                            ProductId = new Guid("b8e0f4c7-3abe-4707-994b-1aa8e959e458"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("4d1d1957-276f-4d4f-903b-f1aa84d689f3"),
                            FridgeId = new Guid("70a4261b-bb48-438e-afd4-3b77bbf681fa"),
                            ProductId = new Guid("26551416-60d1-479b-8254-296b43b00f93"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("614bdcca-e692-484c-a77c-38adaa1d425c"),
                            FridgeId = new Guid("767da512-da4c-4493-88a6-69fcdb7119a3"),
                            ProductId = new Guid("23b60a97-dd73-4e06-a19e-fccb299d5fdf"),
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("FridgeManager.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1013bc0a-821b-4880-a911-cca740cd8616"),
                            DefaultQuantity = 14,
                            Name = "Bread"
                        },
                        new
                        {
                            Id = new Guid("b8e0f4c7-3abe-4707-994b-1aa8e959e458"),
                            DefaultQuantity = 9,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("8e83ae7b-760e-4e83-a5fa-862614908cca"),
                            DefaultQuantity = 6,
                            Name = "Yoghurt"
                        },
                        new
                        {
                            Id = new Guid("5ca1249a-e85b-4c1f-a905-8491904144ef"),
                            DefaultQuantity = 8,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = new Guid("799f487a-df41-4bd6-86bf-5e00d7b02941"),
                            DefaultQuantity = 11,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = new Guid("bc4d80f3-64b1-404b-8944-b7afd2823f0a"),
                            DefaultQuantity = 6,
                            Name = "Mashroom"
                        },
                        new
                        {
                            Id = new Guid("256e2500-3c66-47ad-a2f7-410b33552aea"),
                            DefaultQuantity = 14,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = new Guid("166160aa-2cf5-4635-b7ee-1d43b7be2463"),
                            DefaultQuantity = 9,
                            Name = "Pork"
                        },
                        new
                        {
                            Id = new Guid("3ecb1585-78ca-4105-b96c-a1eb56527838"),
                            DefaultQuantity = 10,
                            Name = "Beef"
                        },
                        new
                        {
                            Id = new Guid("375601c3-051a-4d8c-8c56-f6515d481d82"),
                            DefaultQuantity = 15,
                            Name = "Sausage"
                        },
                        new
                        {
                            Id = new Guid("77fa2bef-4774-4bbe-8eb2-7cfd9c87ae9d"),
                            DefaultQuantity = 16,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("66e6180f-6800-4529-be7e-fe94cf1a54ca"),
                            DefaultQuantity = 11,
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = new Guid("5a0c43b4-e5c9-4733-96ce-838a36869e5d"),
                            DefaultQuantity = 7,
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = new Guid("1d98c8d2-e0fb-41b5-b9d7-80191cb89e3e"),
                            DefaultQuantity = 15,
                            Name = "Beans"
                        },
                        new
                        {
                            Id = new Guid("c8046b78-b45e-4b92-b176-dc4b33851105"),
                            DefaultQuantity = 16,
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = new Guid("23b60a97-dd73-4e06-a19e-fccb299d5fdf"),
                            DefaultQuantity = 17,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = new Guid("e65fc433-443b-4657-850b-0e51305dee31"),
                            DefaultQuantity = 5,
                            Name = "Onion"
                        },
                        new
                        {
                            Id = new Guid("09bcc40f-4987-4a41-aa4c-b181404984a4"),
                            DefaultQuantity = 13,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = new Guid("16f92d8b-d8de-409d-87a6-58743a0291c8"),
                            DefaultQuantity = 8,
                            Name = "Potato"
                        },
                        new
                        {
                            Id = new Guid("bdda92b3-5e80-40cd-8dcd-9b1b2e2b473b"),
                            DefaultQuantity = 16,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = new Guid("46afdfa9-b130-4600-b389-17586ddd7021"),
                            DefaultQuantity = 12,
                            Name = "Cherry"
                        },
                        new
                        {
                            Id = new Guid("67e975f4-973e-4a2a-ab4c-3b56523c99db"),
                            DefaultQuantity = 6,
                            Name = "Grape"
                        },
                        new
                        {
                            Id = new Guid("63cf83af-dad8-4194-88e9-39be803f7678"),
                            DefaultQuantity = 14,
                            Name = "Lemon"
                        },
                        new
                        {
                            Id = new Guid("a1f996e4-e463-44fa-9f35-cf55aa53d8cc"),
                            DefaultQuantity = 15,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = new Guid("116741f5-917f-475b-9cb1-120d4c55caef"),
                            DefaultQuantity = 17,
                            Name = "Peach"
                        },
                        new
                        {
                            Id = new Guid("47a3cd4c-708f-4b1d-aa2e-1e4bc2c29d55"),
                            DefaultQuantity = 11,
                            Name = "Strawberry"
                        },
                        new
                        {
                            Id = new Guid("e8f8756a-2672-4d6d-8d8d-a58beaaa7ce2"),
                            DefaultQuantity = 12,
                            Name = "Raspberry"
                        },
                        new
                        {
                            Id = new Guid("1719d983-68fb-4ebf-9ac3-ac52dd78f052"),
                            DefaultQuantity = 6,
                            Name = "Watermelon"
                        },
                        new
                        {
                            Id = new Guid("26551416-60d1-479b-8254-296b43b00f93"),
                            DefaultQuantity = 9,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = new Guid("29cc9704-537f-4fdb-828a-d79316737017"),
                            DefaultQuantity = 16,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("a132254c-85de-4b5c-9a6e-f1c133292b5c"),
                            DefaultQuantity = 17,
                            Name = "Kefir"
                        },
                        new
                        {
                            Id = new Guid("b8c66265-ae6b-40d4-a4e6-e8f0fca2820b"),
                            DefaultQuantity = 14,
                            Name = "Chokolate"
                        },
                        new
                        {
                            Id = new Guid("430a93be-3ce6-45f6-8247-658d44f1f490"),
                            DefaultQuantity = 9,
                            Name = "Jam"
                        },
                        new
                        {
                            Id = new Guid("13a10290-240e-4bae-bc72-129275177cf2"),
                            DefaultQuantity = 17,
                            Name = "Pudding"
                        },
                        new
                        {
                            Id = new Guid("918368ca-4c27-4268-881f-3bed5dacd96f"),
                            DefaultQuantity = 6,
                            Name = "Jelly"
                        },
                        new
                        {
                            Id = new Guid("34dd94be-13a4-49bd-abfb-56fadf786c99"),
                            DefaultQuantity = 7,
                            Name = "Pancake"
                        },
                        new
                        {
                            Id = new Guid("6f8505df-6a22-40c1-8f27-851fe5ee8fe7"),
                            DefaultQuantity = 10,
                            Name = "Juice"
                        },
                        new
                        {
                            Id = new Guid("70cb93dd-a516-4964-9743-4c056b4ab3a8"),
                            DefaultQuantity = 11,
                            Name = "Soda"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FridgeManager.Domain.Models.Fridge", b =>
                {
                    b.HasOne("FridgeManager.Domain.Models.FridgeModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("FridgeManager.Domain.Models.FridgeProduct", b =>
                {
                    b.HasOne("FridgeManager.Domain.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeManager.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FridgeManager.Domain.Models.Authorization.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FridgeManager.Domain.Models.Authorization.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeManager.Domain.Models.Authorization.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FridgeManager.Domain.Models.Authorization.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
